DROP TABLE users;
DROP TABLE accounts;
DROP TABLE payments;
DROP TABLE cards;
DROP TABLE requests;
DROP TABLE logs;
DROP TYPE users_status_type;
DROP TYPE users_role_type;
DROP TYPE accounts_currency_type;
DROP TYPE accounts_status_type;
DROP TYPE payments_status_type;
DROP TYPE requests_status_type